apiPort: 0
bindings:
- name: bridge-1
  properties: {}
  sources:
    connections:
    - address: kubemq-cluster-grpc.kubemq:50000
      channel: sad
      setDefaults: "true"
    kind: source.queue-stream
  targets:
    connections:
    - address: kubemq-cluster-grpc.kubemq:50000
      default_channel: asd
      setDefaults: "true"
    kind: target.command
logLevel: ""
