apiPort: 8081
bindings:
#  - name: kubemq-query-redis
#    source:
#      kind: source.query
#      name: kubemq-query
#      properties:
#        host: "localhost"
#        port: "50000"
#        client_id: "kubemq-query-redis-connector"
#        auth_token: ""
#        channel: "query.redis"
#        group:   ""
#        concurrency: "1"
#        auto_reconnect: "true"
#        reconnect_interval_seconds: "1"
#        max_reconnects: "0"
#    target:
#      kind: target.cache.redis
#      name: target-redis
#      properties:
#        host: "localhost:6379"
#        password: ""
#        enable_tls: "false"
#    properties:
#      log_level: "error"
#      rate_per_seconds: "1"
#      retry_attempts:  "3"
#      retry_delay_milliseconds :      "100"
#      retry_max_jitter_milliseconds: "100"
#      retry_delay_type: "fixed"
#  - name: kubemq-query-memcached
#    source:
#      kind: source.query
#      name: kubemq-query
#      properties:
#        host: "localhost"
#        port: "50000"
#        client_id: "kubemq-query-memcached-connector"
#        auth_token: ""
#        channel: "query.memcached"
#        group:   ""
#        concurrency: "1"
#        auto_reconnect: "true"
#        reconnect_interval_seconds: "1"
#        max_reconnects: "0"
#    target:
#      kind: target.cache.memcached
#      name: target-memcached
#      properties:
#        hosts: "localhost:11211"
#        max_idle_connections: "2"
#        default_timeout_seconds: "10"
#    properties:
#      log_level: "error"
#  - name: kubemq-query-OpenFaas
#    source:
#      kind: source.query
#      name: kubemq-query
#      properties:
#        host: "localhost"
#        port: "50000"
#        client_id: "kubemq-query-OpenFaas-connector"
#        auth_token: ""
#        channel: "query.openfaas"
#        group:   ""
#        concurrency: "1"
#        auto_reconnect: "true"
#        reconnect_interval_seconds: "1"
#        max_reconnects: "0"
#    target:
#      kind: target.serverless.openfaas
#      name: target-serverless-openfaas
#      properties:
#        gateway: "http://localhost:31112"
#        username: "admin"
#        password: "password"
#    properties : {}
#  - name: kubemq-query-http
#    source:
#      kind: source.query
#      name: kubemq-query
#      properties:
#        host: "localhost"
#        port: "50000"
#        client_id: "kubemq-query-http-connector"
#        auth_token: ""
#        channel: "query.http"
#        group:   ""
#        concurrency: "1"
#        auto_reconnect: "true"
#        reconnect_interval_seconds: "1"
#        max_reconnects: "0"
#    target:
#      kind: target.http
#      name: target-http
#      properties:
#        auth_type: "no-auth"
#        default_headers: '{"Content-Type":"application/json"}'
#    properties:
#      log_level: "error"
#  - name: kubemq-query-postgres
#    source:
#      kind: source.query
#      name: kubemq-query
#      properties:
#        host: "localhost"
#        port: "50000"
#        client_id: "kubemq-query-postgres-connector"
#        auth_token: ""
#        channel: "query.postgres"
#        group:   ""
#        concurrency: "1"
#        auto_reconnect: "true"
#        reconnect_interval_seconds: "1"
#        max_reconnects: "0"
#    target:
#      kind: target.stores.postgres
#      name: target-postgres
#      properties:
#        connection: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
#        max_idle_connections: "10"
#        max_open_connections: "100"
#        connection_max_lifetime_seconds: "3600"
#    properties:
#      log_level: "error"
#  - name: kubemq-query-mysql
#    source:
#      kind: source.query
#      name: kubemq-query
#      properties:
#        host: "localhost"
#        port: "50000"
#        client_id: "kubemq-query-mysql-connector"
#        auth_token: ""
#        channel: "query.mysql"
#        group:   ""
#        concurrency: "1"
#        auto_reconnect: "true"
#        reconnect_interval_seconds: "1"
#        max_reconnects: "0"
#    target:
#      kind: target.stores.mysql
#      name: target-mysql
#      properties:
#        connection: "root:mysql@(localhost:3306)/store?charset=utf8&parseTime=True&loc=Local"
#        max_idle_connections: "10"
#        max_open_connections: "100"
#        connection_max_lifetime_seconds: "3600"
#    properties:
#      log_level: "error"
#  - name: kubemq-query-mssql
#    source:
#      kind: source.query
#      name: kubemq-query
#      properties:
#        host: "localhost"
#        port: "50000"
#        client_id: "kubemq-query-mssql-connector"
#        auth_token: ""
#        channel: "query.mssql"
#        group:   ""
#        concurrency: "1"
#        auto_reconnect: "true"
#        reconnect_interval_seconds: "1"
#        max_reconnects: "0"
#    target:
#      kind: target.stores.mssql
#      name: target-mssql
#      properties:
#        connection: "sqlserver://sa:n8x2Nz!f@localhost:1433?database=master"
#        max_idle_connections: "10"
#        max_open_connections: "100"
#        connection_max_lifetime_seconds: "3600"
#    properties:
#      log_level: "error"
#  - name: kubemq-query-mongodb
#    source:
#      kind: source.query
#      name: kubemq-query
#      properties:
#        host: "localhost"
#        port: "50000"
#        client_id: "kubemq-query-mongodb-connector"
#        auth_token: ""
#        channel: "query.mongodb"
#        group:   ""
#        concurrency: "1"
#        auto_reconnect: "true"
#        reconnect_interval_seconds: "1"
#        max_reconnects: "0"
#    target:
#      kind: target.stores.mongodb
#      name: target-mongodb
#      properties:
#        host: "localhost:27017"
#        username: "admin"
#        password: "password"
#        database: "admin"
#        collection: "test"
#        write_concurrency: "majority"
#        read_concurrency: ""
#        params: ""
#        operation_timeout_seconds: "2"
#    properties :
#      log_level: "error"
#  - name: kubemq-query-couchbase
#    source:
#      kind: source.query
#      name: kubemq-query
#      properties:
#        host: "localhost"
#        port: "50000"
#        client_id: "kubemq-query-couchbase-connector"
#        auth_token: ""
#        channel: "query.couchbase"
#        group:   ""
#        concurrency: "1"
#        auto_reconnect: "true"
#        reconnect_interval_seconds: "1"
#        max_reconnects: "0"
#    target:
#      kind: target.stores.couchbase
#      name: target-couchbase
#      properties:
#        url: "localhost"
#        username: "couchbase"
#        password: "couchbase"
#        bucket: "bucket"
#        collection: ""
#        num_to_replicate: "1"
#        num_to_persist: "1"
#    properties:
#      log_level: "error"
#  - name: kubemq-query-minio
#    source:
#      kind: source.query
#      name: kubemq-query
#      properties:
#        host: "localhost"
#        port: "50000"
#        client_id: "kubemq-query-minio-connector"
#        auth_token: ""
#        channel: "query.minio"
#        group:   ""
#        concurrency: "1"
#        auto_reconnect: "true"
#        reconnect_interval_seconds: "1"
#        max_reconnects: "0"
#    target:
#      kind: target.storage.minio
#      name: target-minio
#      properties:
#        endpoint: "localhost:9001"
#        use_ssl: "false"
#        access_key_id: "minio"
#        secret_access_key: "minio123"
#    properties:
#      log_level: "error"
#  - name: kubemq-query-cassandra
#    source:
#      kind: source.query
#      name: kubemq-query
#      properties:
#        host: "localhost"
#        port: "50000"
#        client_id: "kubemq-query-cassandra-connector"
#        auth_token: ""
#        channel: "query.cassandra"
#        group:   ""
#        concurrency: "1"
#        auto_reconnect: "true"
#        reconnect_interval_seconds: "1"
#        max_reconnects: "0"
#    target:
#      kind: target.stores.cassandra
#      name: target-cassandra
#      properties:
#        hosts: "localhost"
#        port: "9042"
#        username: "cassandra"
#        password: "cassandra"
#        proto_version: "4"
#        replication_factor: "1"
#        consistency: "All"
#        default_table: "test"
#        default_keyspace: "test"
#    properties:
#      log_level: "error"
#  - name: kubemq-query-rabbitmq
#    source:
#      kind: source.query
#      name: kubemq-query
#      properties:
#        host: "localhost"
#        port: "50000"
#        client_id: "kubemq-query-rabbitmq-connector"
#        auth_token: ""
#        channel: "query.rabbitmq"
#        group:   ""
#        concurrency: "1"
#        auto_reconnect: "true"
#        reconnect_interval_seconds: "1"
#        max_reconnects: "0"
#    target:
#      kind: target.messaging.rabbitmq
#      name: target-rabbitmq
#      properties:
#        url: "amqp://rabbitmq:rabbitmq@localhost:5672/"
#    properties:
#      log_level: "error"
#  - name: kubemq-query-mqtt
#    source:
#      kind: source.query
#      name: kubemq-query
#      properties:
#        host: "localhost"
#        port: "50000"
#        client_id: "kubemq-query-mqtt-connector"
#        auth_token: ""
#        channel: "query.mqtt"
#        group:   ""
#        concurrency: "1"
#        auto_reconnect: "true"
#        reconnect_interval_seconds: "1"
#        max_reconnects: "0"
#    target:
#      kind: target.messaging.mqtt
#      name: target-mqtt
#      properties:
#        host: "localhost:1883"
#        username: "username"
#        password: "password"
#        client_id: "client_id"
#    properties:
#      log_level: "error"
#  - name: kubemq-query-activemq
#    source:
#      kind: source.query
#      name: kubemq-query
#      properties:
#        host: "localhost"
#        port: "50000"
#        client_id: "kubemq-query-activemq-connector"
#        auth_token: ""
#        channel: "query.activemq"
#        group:   ""
#        concurrency: "1"
#        auto_reconnect: "true"
#        reconnect_interval_seconds: "1"
#        max_reconnects: "0"
#    target:
#      kind: target.messaging.activemq
#      name: target-activemq
#      properties:
#        host: "localhost:61613"
#        username: ""
#        password: ""
#    properties:
#      log_level: "error"
  - name: kubemq-query-elastic-search
    source:
      kind: source.query
      name: kubemq-query
      properties:
        host: "localhost"
        port: "50000"
        client_id: "kubemq-query-elastic-search-connector"
        auth_token: ""
        channel: "query.elastic-search"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.stores.elastic-search
      name: target-elastic-search
      properties:
        urls: "http://localhost:9200"
        username: "admin"
        password: "password"
        sniff: "false"
    properties:
      log_level: "debug"
      rate_per_seconds: "10"
      retry_attempts:  "3"
      retry_delay_milliseconds :      "100"
      retry_max_jitter_milliseconds: "100"
      retry_delay_type: "fixed"
