bindings:
- name: as
  properties: null
  sources:
    Connections:
    - address: localhost:50000
      channel: source.da.queuess
    Kind: source.queue
    Name: da
  targets:
    Connections:
    - address: localhost:50000
      channels: target.sd.queues
    Kind: target.queue
    Name: sds
- name: as
  properties: null
  sources:
    Connections:
      - address: localhost:50000
        channel: source.da.queues
    Kind: source.queue
    Name: da
  targets:
    Connections:
      - address: localhost:50000
        channels: target.sd.queues
    Kind: target.queue
    Name: sd

