bindings:
- name: as
  properties:
    log_level: "debug"
  sources:
    Connections:
    - address: localhost:50000
      channel: source1
    Kind: source.queue
    Name: da
  targets:
    Connections:
    - address: localhost:50000
      channels: target1
    Kind: target.queue
    Name: sds
- name: as2344
  properties:
    log_level: "debug"
  sources:
    Connections:
      - address: localhost:50000
        channel: target1
    Kind: source.queue
    Name: da
  targets:
    Connections:
      - address: localhost:50000
        channels: target2
    Kind: target.queue
    Name: sd

