apiPort: 8081
bindings:
  - name: cluster-a-d-events
    source:
      kind: source.events
      name: cluster-a-events-source
      properties:
        address: "localhost:30501"
        client_id: "cluster-a-events-source"
        auth_token: ""
        channel: "events.a"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.events
      name: cluster-a-d-events-target
      properties:
        address: "localhost:30504"
        client_id: "cluster-a-d-events-target"
        auth_token: ""
        channels: "events.aggregate"
    properties:
      log_level: "debug"
  - name: cluster-b-d-events
    source:
      kind: source.events
      name: cluster-b-events-source
      properties:
        address: "localhost:30502"
        client_id: "cluster-b-events-source"
        auth_token: ""
        channel: "events.b"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.events
      name: cluster-b-d-events-target
      properties:
        address: "localhost:30504"
        client_id: "cluster-b-d-events-target"
        auth_token: ""
        channels: "events.aggregate"
    properties:
      log_level: "debug"
  - name: cluster-c-d-events
    source:
      kind: source.events
      name: cluster-c-events-source
      properties:
        address: "localhost:30503"
        client_id: "cluster-c-d-events-source"
        auth_token: ""
        channel: "events.c"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.events
      name: cluster-c-d-events-target
      properties:
        address: "localhost:30504"
        client_id: "cluster-c-d-events-target"
        auth_token: ""
        channels: "events.aggregate"
    properties:
      log_level: "debug"
  - name: cluster-d-e-queue
    source:
      kind: source.queue
      name: cluster-d-queue-source
      properties:
        address: "localhost:30504"
        client_id: "cluster-d-queue-source"
        auth_token: ""
        channel: "queue.e"
    target:
      kind: target.queue
      name: cluster-e-queue-target
      properties:
        address: "localhost:30505"
        client_id: "cluster-e-queue-target"
        auth_token: ""
        channels: "queue"
    properties:
      log_level: "debug"
  - name: cluster-d-f-queue
    source:
      kind: source.queue
      name: cluster-d-queue-source
      properties:
        address: "localhost:30504"
        client_id: "cluster-d-queue-source"
        auth_token: ""
        channel: "queue.f"
    target:
      kind: target.queue
      name: cluster-f-queue-target
      properties:
        address: "localhost:30506"
        client_id: "cluster-f-queue-target"
        auth_token: ""
        channels: "queue"
    properties:
      log_level: "debug"
  - name: cluster-d-g-queue
    source:
      kind: source.queue
      name: cluster-d-queue-source
      properties:
        address: "localhost:30504"
        client_id: "cluster-d-queue-source"
        auth_token: ""
        channel: "queue.g"
    target:
      kind: target.queue
      name: cluster-g-queue-target
      properties:
        address: "localhost:30507"
        client_id: "cluster-g-queue-target"
        auth_token: ""
        channels: "queue"
    properties:
      log_level: "debug"
