apiPort: 8081
bindings:
  - name: cluster-a-b-events
    source:
      kind: source.events
      name: cluster-a-events-source
      properties:
        address: "localhost:30501"
        client_id: "cluster-a-events-source"
        auth_token: ""
        channel: "events"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.events
      name: cluster-b-events-target
      properties:
        address: "localhost:30502"
        client_id: "cluster-b-events-target"
        auth_token: ""
        channels: "events.b.1,events.b.2"
    properties:
      log_level: "debug"
  - name: cluster-a-c-events
    source:
      kind: source.events
      name: cluster-a-events-source
      properties:
        address: "localhost:30501"
        client_id: "cluster-a-events-source"
        auth_token: ""
        channel: "events"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.events
      name: cluster-c-events-target
      properties:
        address: "localhost:30503"
        client_id: "cluster-c-events-target"
        auth_token: ""
        channels: "events.c.1,events.c.2"
    properties:
      log_level: "debug"
  - name: cluster-a-d-events
    source:
      kind: source.events
      name: cluster-a-events-source
      properties:
        address: "localhost:30501"
        client_id: "cluster-a-events-source"
        auth_token: ""
        channel: "events"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.events
      name: cluster-d-events-target
      properties:
        address: "localhost:30504"
        client_id: "cluster-c-events-target"
        auth_token: ""
        channels: "events.d.1,events.d.2"
    properties:
      log_level: "debug"
